#!/bin/sh

if ! type "ansible-playbook" > /dev/null; then
  echo "Ansible not found. Please install Ansible."
  exit 1
fi

# echo "Locating Rpi in your network"
# python ../bin/rpifind

echo "Installing SITM in the Rpi"
ansible-playbook -c paramiko -i ansible/hosts ansible/main.yml --sudo --limit @/Users/zilog/development/projects/sitm/provision/ansible/main.retry
