#! /bin/sh

### BEGIN INIT INFO
# Provides:          sitmd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start 'Something in the Middle' as a daemon
# Description:       Control the 'sitmd' daemon.
### END INIT INFO

# @todo any command placed here will run unconditionally

DAEMON="sitmd"

case "$1" in
  start)
    echo "Starting $DAEMON"
    # run application you want to start
    /usr/local/bin/sitmd
    ;;
  stop)
    echo "Stopping $DAEMON"
    # kill application you want to stop
    killall sitmd
    ;;
  *)
    echo "Usage: /etc/init.d/sitmd {start|stop}"
    exit 1
    ;;
esac

exit 0
