#!/usr/bin/env bash

PACKAGES_BASE="unattended-upgrades curl htop nmap tmux zsh nmon rpi-update haveged avahi-daemon rng-tools vim sqlite3 git mc build-essential python-dev python-pip python-smbus tcpdump"

base_config() {
  nfo "Changing hostname"
  echo "sitm" > /etc/hostname
  echo "127.0.1.1   sitm" >> /etc/hosts

  nfo "Generate locales to prevent annoying SSH messages"
  locale-gen "en_US.UTF-8"
  dpkg-reconfigure locales

  nfo "Removing Wolfram Alpha, it's big and we don't need it"
  apt-get remove --purge wolfram-alpha

  apt_install_deps $PACKAGES_BASE

  nfo "Clean and refresh apt cache"
  apt-get clean && apt-get update

  nfo "Autoremove any unused packages and autoclean the apt system"
  apt-get autoremove --assume-yes --purge
  apt-get autoclean --assume-yes
}
