#!/usr/bin/env bash

ssh_key_generate() {
  info "We are going to generate an SSH key for our RPi"
  ssh-keygen -f ~/.ssh/id_rpi_default -t rsa -C "sitm@alternativelearningtank.net" -b 4096
}

# params:
#   $1 -> Rpi hostname/ip

ssh_key_install() {
  info "Installing RPi default SSH key i RPi host at $1"
  cat ~/.ssh/id_rpi_default.pub | ssh pi@$1 'cat - >> ~/.ssh/authorized_keys'
}
