#!/usr/bin/env bash

ssh_key_generate() {
  nfo "We are going to generate an SSH key for our RPi"
  ssh-keygen -f ~/.ssh/id_rpi_default -t rsa -C "someone@sitm.local" -b 4096
}

# params:
#   $1 -> Rpi hostname/ip
ssh_key_install() {
  nfo "Installing RPi default SSH key i RPi host at $1"
  cat ~/.ssh/id_rpi_default.pub | ssh someone@$1 'mkdir -p ~/.ssh && cat - >> ~/.ssh/authorized_keys'
}
